@startuml
interface ICodeCompiler {
    CompileCode(code:IReadOnlyCollection<string>, assemblyTags:IReadOnlyCollection<Type>) : Assembly
    CompileCode(code:IReadOnlyCollection<string>) : Assembly
}
@enduml
