@startuml
class ProtocCodeGenerator {
    {static} - ProtocCodeGenerator()
    - {static} DetectBinPath(assembly:Assembly, resourcePath:string, targetDirPath:string) : string
    - {static} ThrowNotSupported() : void
    - {static} s_protocPath : string
    - {static} s_grpcPluginPath : string
    - GenerateCodeFromProto(root:string, files:string[]) : Task<IReadOnlyCollection<string>>
    - GenerateCodeFromProto(root:string, files:IEnumerable<string>) : Task<IReadOnlyCollection<string>>
    - <<async>> GenerateCodeFromProtoImpl(root:string, files:IEnumerable<string>) : Task<IReadOnlyCollection<string>>
}
ICodeGenerator <|-- ProtocCodeGenerator
@enduml
