@startuml
class ProtoGenerator {
    + {static} CreateDefault() : ProtoGenerator
    + ProtoGenerator(codeCompiler:ICodeCompiler, codeGenerator:ICodeGenerator)
    - GenerateAll(root:string, directories:IEnumerable<string>) : Task<Assembly>
    - Generate(root:string, files:string[]) : Task<Assembly>
    - Generate(root:string, files:IEnumerable<string>) : Task<Assembly>
    - <<async>> GenerateImpl(root:string, files:IEnumerable<string>) : Task<Assembly>
}
IProtoGenerator <|-- ProtoGenerator
ProtoGenerator --> "_codeCompiler" ICodeCompiler
ProtoGenerator --> "_codeGenerator" ICodeGenerator
@enduml
